default: 	cpsc2150/connectX/ConnectXApp.java cpsc2150/connectX/ConnectXController.java cpsc2150/connectX/ConnectXView.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/IGameBoard.java cpsc2150/connectX/GameBoardMem.java cpsc2150/connectX/SetupView.java cpsc2150/connectX/SetupController.java

	javac cpsc2150/connectX/ConnectXApp.java cpsc2150/connectX/ConnectXController.java cpsc2150/connectX/ConnectXView.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/IGameBoard.java cpsc2150/connectX/GameBoardMem.java cpsc2150/connectX/SetupView.java cpsc2150/connectX/SetupController.java

run: 	cpsc2150/connectX/ConnectXApp.class cpsc2150/connectX/ConnectXController.class cpsc2150/connectX/ConnectXView.class cpsc2150/connectX/GameBoard.class cpsc2150/connectX/IGameBoard.class cpsc2150/connectX/GameBoardMem.class cpsc2150/connectX/SetupView.class cpsc2150/connectX/SetupController.class
	java cpsc2150.connectX.ConnectXApp

clean:
	rm cpsc2150/connectX/ConnectXApp.class
	rm cpsc2150/connectX/ConnectXController.class
	rm cpsc2150/connectX/ConnectXView.class
	rm cpsc2150/connectX/GameBoard.class
	rm cpsc2150/connectX/IGameBoard.class
	rm cpsc2150/connectX/GameBoardMem.class
	rm cpsc2150/connectX/SetupView.class
	rm cpsc2150/connectX/SetupController.class
